### ISSUE TITLE
"record type is SSL3_AL_FATAL" is occurred

### ISSUE THREAD

**Issue by matxxxx** [hirose31/Net-SSL-ExpireDate#5]
#!/usr/bin/env perl
    
    use strict;
    use warnings;
    
    use Net::SSL::ExpireDate;
    
    my $ed = Net::SSL::ExpireDate->new(https=>'www.28083.jp');
    if ($ed->expire_date) {
         print $ed->expire_date;
    }
    else {
         print "Error!\n";
    }
    
    
    # Expected behaviour: prints expiration date of https://www.28083.jp/ certificate
    #
    # Actual behaviour:  prints
    #   record type is SSL3_AL_FATAL at ./a.pl line 9
    #   Error!
    #
    # Perl v5.10.1 (*) built for x86_64-linux-thread-multi
    # Net::SSL::ExpireDate 1.17
    #

**Comment by hirose31** [comment]
@matxxxx 

I've just release v1.18, could you try with this version?
