### ISSUE TITLE
Can't locate object method "ExpireDate"

### ISSUE THREAD

**Issue by MikeCockrem** [hirose31/Net-SSL-ExpireDate#7]
Hi,

Having some problems with this (it could well be my misunderstanding) I get the following error:

> Can't locate object method "ExpireDate" via package "Net::SSL::ExpireDate" at
>         LetsEnscript.pl line 134 (#1)
>     (F) You called a method correctly, and it correctly indicated a package
>     functioning as a class, but that package doesn't define that particular
>     method, nor does any of its base classes.  See perlobj.
>     
> Uncaught exception from user code:
>         Can't locate object method "ExpireDate" via package "Net::SSL::ExpireDate" at LetsEnscript.pl line 134.
>  at LetsEnscript.pl line 134
>         main::CheckExpiry() called at LetsEnscript.pl line 101
>

Here is the code snippet in question:

```
sub CheckExpiry {
    $ExpiryCheck = Net::SSL::ExpireDate->new( file => '/srv/irc/conf/ssl/mycert.pem' );

    if (defined $ExpiryCheck->ExpireDate) {
            $ExpireDate = $ExpiryCheck->ExpireDate;
            $Expired = $ExpiryCheck->is_expired($ExpiryDeadline);
            if (not defined $Expired) { die "Not expired\n"; } # Leave script
    } else {
            die "Could not establish certificate expiry dates\n";
    }
}
```

I also have issues using file => '$some/$variables'  which doesn't work at all, but right now I'm more concerned with the above.

Here is the original context of the code, where I'm calling it (please excuse the non-programmer level of quality :-)  [github repo](https://github.com/MikeCockrem/unreal-ssl-bot/blob/master/LetsEnscript.pl)

**Version info:**
 cpanm Net::SSL::ExpireDate
Net::SSL::ExpireDate is up to date. (1.20)
perl --version
This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi
cat /etc/centos-release 
CentOS release 6.9 (Final)

Any advice is appreciated, thanks kindly.

Mike.

**Comment by hirose31** [comment]
Try to use `->expire_date` instead of `->ExpireDate`.

```perl
    if (defined $ExpiryCheck->ExpireDate) {
            $ExpireDate = $ExpiryCheck->ExpireDate;
```
↓
```perl
    if (defined $ExpiryCheck->expire_date) {
            $ExpireDate = $ExpiryCheck->expire_date;
```

**Comment by MikeCockrem** [comment]
Works perfectly, thanks!
